### ISSUE TITLE
Smartgrab Feature

### ISSUE THREAD

**Issue by itotallyrock** [plugCubed/plugCubed#143]
I've put some time into creating a SmartGrab feature that grabs if a certain percentage of the community grabs and woots, while there is a minimum difference between mehs and grabs.

Example:
`Minimum 3% of audience of 150 = 5 Grabs` is the first test
`30% of audience of 150 = 45 Woots`
And there are 2 mehs on the song with a set requirement of 3 difference
`5 (Grabs) - 2 (Mehs) >= 3 (Maximum difference)` returns true

This would then grab a preset playlist.
I was wondering if I should put more effort into it becoming a full feature.  If so I would polish it up to look nice and possibly create more settings or room settings for it.

Let me know if I should keep working on it or at least if I should stop wasting my time. :smile:

**Comment by thedark1337** [comment]
While i like the idea, there is a lot that would go against the feature.

For example, almost everyone uses an autowoot (majority have delays set as well) , how would smartgrab account for that?  What if the song gets skipped, or the DJ gets disconnected, will it still grab? 

I'm also not sure how many people would use a "smartgrab" feature.

Thank you for the idea

**Comment by Exuviax** [comment]
Hello :)

I like the idea of a more in-depth Auto-grab. However, much like TheDark said, it's not viable to use the total room Woot's as most rooms have a lot of the audience auto-wooting. 

So I have a suggestion, how about instead of the room we look at the person who has the extension enabled. If they have woot'ed a song more than a certain number of times in any room it auto-grabs to a specified playlist (Say I have a playlist "Auto-grabbed" and I want all my auto's to go there). It could even go more in-depth and grab it based on a percentage if there are ten people on the waitlist, the woot counts for one vote towards grabbing the song, however, if there are 40 people it counts for four votes to grab. After ten votes, the song is grabbed.

Just and idea :)

**Comment by thedark1337** [comment]
Unfortunately upon further discussion on the slack team with other users, there doesn't seem to be much support of the addition of a smartGrab feature. Apologies if you've already worked on it.   We're always welcome to other ideas if you have any however

- TheDark1337
